### ISSUE TITLE
Gitpod loading Wagtail 3.0 instead of 3.0.1

### ISSUE THREAD

**Issue by vossisboss** [wagtail/wagtail-gitpod#13]
For some reason, Gitpod is loading Wagtail 3.0 instead of the latest stable version, which is 3.0.1. Flagging this here so we can investigate why this might be if this behavior continues after the next release.

![Screen Shot 2022-08-15 at 4 11 25 PM](https://user-images.githubusercontent.com/45881480/184710566-4b2c30f7-0303-4202-b502-63ca364318ed.png)

**Comment by thibaudcolas** [comment]
I can reproduce this as well, and would assume the same thing will happen for the 4.0 release. I suspect this might be related to Gitpod prebuilds – since we build our own image, there is caching involved, and I’m not sure how we invalidate the cache currently.

This repository doesn’t seem to be part of https://gitpod.io/t/wagtail/projects on Gitpod. @allcaps I assume you’ll have the required access and Gitpod knowledge to help with this?

**Comment by allcaps** [comment]
This is because Gitpod has a pre-build feature that acts as a cache. There are ways to invalidate the pre-build. I don't have time to look into it. A PR will probably have it's own build and thus the correct version.

**Comment by allcaps** [comment]
I refreshed the pre-build with  https://gitpod.io/#prebuild/https://github.com/wagtail/wagtail-gitpod, we are now on 3.0.1

**Comment by vossisboss** [comment]
So will the pre-build need to be refreshed with each new release?
